### PR TITLE
Added the Dark theme toggle

### PR DESCRIPTION
**Pull request by suppixie**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Fixes issue #14 

We have added a responsive dark theme toggle . It also supports the system default theme.

Screenshots:
dark mode
light mode

Co-authored by @k-abirami

### CODE REVIEW

**Comment by akshgpt7** [comment]
Hey, looks pretty good! The button just seems to be oddly positioned, can you fix that and I'll merge it!

image

**Comment by akshgpt7** [comment]
One suggestion would be to add it to the navbar instead of making it float. Or if you want it to be floating, maybe put it at the bottom?

**Comment by suppixie** [comment]
Hey @akshgpt7 , I have changed the position of the toggle to the bottom of the page.

**Comment by akshgpt7** [comment]
Works so well! Thanks for picking this up.

**Pull request merged**
