### PR TITLE
Fix - Replaces the MLH Fellowship logo with the MLH Prep logo

### LINKED ISSUE #5: Replace the MLH Fellowship logo with the MLH Prep logo
Screenshot 2021-09-30 at 18 38 57

When you go to the project page, it shows the MLH Fellowship logo at the top. It would be great to replace this with the Prep logo and make sure that's used throughout the website!

### PR DESCRIPTION
**Pull request by void-ness**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Fixes #5 

The page which had the bug - `http://127.0.0.1:4000/projects/project`

Screenshots after resolving the bug: 
image
(Web view)

image
(Mobile view)

### CODE REVIEW

**Comment by void-ness** [comment]
Hey @akshgpt7 , Me and @archikirar30 have fixed the issue. Kindly review the changes. Thanks.

**Comment by akshgpt7** [comment]
@void-ness @archikirar30 thanks for taking this up, can you just add a little bit of padding-bottom to the logo. That's it :)

**Comment by void-ness** [comment]
> @void-ness @archikirar30 thanks for taking this up, can you just add a little bit of padding-bottom to the logo. That's it :)

Sure. Done with the suggested changes.

**Comment by void-ness** [comment]
Hey @akshgpt7 , We are done with resolving the merge conflicts and the changes suggested by you. Kindly review them. Thanks!

**Comment by akshgpt7** [comment]
LGTM, Thanks!

**Pull request merged**
