### PR TITLE
Add blog

### LINKED ISSUE #7: Add pod blog
It would be awesome to add a blog feature to this repository where fellows can share their insights and people can tune in!

### PR DESCRIPTION
**Pull request by kristinlam**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Fixes #7

### CODE REVIEW

**Comment by akshgpt7** [comment]
Thanks for picking this up!
The blog posts are not showing up on the page for me. Can you look into it and make a fix? 
It'll be ready to merge then.
image

**Comment by kristinlam** [comment]
@akshgpt7, sorry about the confusion. I took all posts out of the _posts folder and put them in _drafts, then made an issue for our pod to start adding real posts. Posts only render if they're in _posts. If you drag one of the draft examples into the _posts folder you should be able to see it.

I can make that change in 30 minutes. But if you are able please let me know if you can test it out sooner. Thank you!

**Comment by akshgpt7** [comment]
Ah gotcha, in that case, you can just resolve the merge conflicts.

**Comment by kristinlam** [comment]
@akshgpt7 I believe I've resolved all the merge conflicts, please let me know if there's an error. Thank you for your help!

**Comment by akshgpt7** [comment]
Looks pretty good! Thanks for adding this.
Great addition 👍 
Let's add some blogs in there

**Pull request merged**
