### PR TITLE
Added cover photo

### PR DESCRIPTION
**Pull request by thatjosh**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

This pull request resolves issue [#3](https://github.com/MLH-Fellowship/prep-portfolio-23.APR.PREP.1/issues/3).

### CODE REVIEW

**Comment by thatjosh** [comment]
Hi @akshgpt7, could you have a look when you are free? Thanks :)

**Comment by akshgpt7** [comment]
@thatjosh can you fix the merge conflicts and push them.
It looks great, but I think some other fellows were working on making the profile pictures responsive, which caused the merge conflict.

**Comment by thatjosh** [comment]
@akshgpt7 just resolved the merge conflicts, thanks!

**Comment by akshgpt7** [comment]
Perfect, thanks a lot!

**Pull request merged**
