### PR TITLE
Ohsweetmani add footer

### PR DESCRIPTION
**Pull request by thatjosh**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by akshgpt7** [comment]
Hey, can you try to push to the same PR?

**Comment by akshgpt7** [comment]
LMK if you face difficulties with it, I'll merge this one then.

**Comment by thatjosh** [comment]
I dont think I can do that because I don't have write access to her repo - but I'll make a note in that PR!

**Comment by akshgpt7** [comment]
Looks great, thanks for completing this!

**Pull request merged**
